/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DoctorRole;

import Schema.Doctor.Doctor;
import Schema.Doctor.PrescriptionList;
import Schema.EcoSystem;
import Schema.Enterprise.Enterprise;
import Schema.Network.Network;
import Schema.Organization.DoctorOrganization;
import Schema.UserAccount.UserAccount;
import Schema.WorkQueue.DoctorWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author amruthaedara
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {
private JPanel userprocessContainer;
private DoctorOrganization docOrg;
private Enterprise ent;
private UserAccount ua;
private Doctor doc;
private PrescriptionList presList;
private DoctorWorkRequest docReq;
private Network ntw;
private EcoSystem system;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount ua, DoctorOrganization docOrg, Enterprise ent, EcoSystem system, Network ntw) {

initComponents();
this.userprocessContainer=userProcessContainer;
this.ua=ua;
this.docOrg=docOrg;

this.ent=ent;
this.ntw=ntw;
this.system=system;
ntw();

    }/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prescriptionBtn = new javax.swing.JButton();
        medicalequipBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        prescriptionBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        prescriptionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/prescription.png"))); // NOI18N
        prescriptionBtn.setText("WRITE PRESCRIPTION");
        prescriptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescriptionBtnActionPerformed(evt);
            }
        });

        medicalequipBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        medicalequipBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steth.png"))); // NOI18N
        medicalequipBtn.setText("MEDICAL EQUIPMENT MANAGEMENT");
        medicalequipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalequipBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doctor1.png"))); // NOI18N
        jLabel1.setText("DOCTOR WORK AREA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prescriptionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medicalequipBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(prescriptionBtn)
                .addGap(95, 95, 95)
                .addComponent(medicalequipBtn)
                .addContainerGap(297, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void medicalequipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalequipBtnActionPerformed
CardLayout crd = (CardLayout) userprocessContainer.getLayout();
userprocessContainer.add("PrescriptionJPanel", new ui.DoctorRole.HealthcareEquipmentManagmentJpanel(userprocessContainer, ua, docOrg,ent,system,ntw));// TODO add your handling code here:
crd.next(userprocessContainer);
    }//GEN-LAST:event_medicalequipBtnActionPerformed

    private void prescriptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionBtnActionPerformed
CardLayout crd = (CardLayout) userprocessContainer.getLayout();
userprocessContainer.add("PrescriptionJPanel", new ui.DoctorRole.PrescriptionJPanel(userprocessContainer,presList,ua,ent,docOrg));// TODO add your handling code here:
crd.next(userprocessContainer);
    }//GEN-LAST:event_prescriptionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton medicalequipBtn;
    private javax.swing.JButton prescriptionBtn;
    // End of variables declaration//GEN-END:variables

    private void ntw() {
ntw.getName();
    }
}
