/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Transportation;

import com.db4o.cs.internal.messages.Message;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Schema.EcoSystem;
import Schema.Organization.Organization;
import Schema.UserAccount.UserAccount;
import Schema.WorkQueue.TransportationWorkRequest;  
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.HealthcareEquipmentWareHouse.ViewTransportationRequestJPanel;





/*
 *
 * @author amruthaedara
 */
import static java.lang.ProcessBuilder.Redirect.to;
public class ProcessRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessRequestJPanel
     */
    
    JPanel userProcessContainer;
    TransportationWorkRequest request;
    private UserAccount userAccount;
    private Organization organization;
    private EcoSystem system;
    
    public ProcessRequestJPanel(JPanel userProcessContainer,TransportationWorkRequest request) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trpaLbl = new javax.swing.JLabel();
        etdLbl = new javax.swing.JLabel();
        timeCmbBox = new javax.swing.JComboBox<>();
        timezoneCmbBox = new javax.swing.JComboBox<>();
        vehiclenumLbl = new javax.swing.JLabel();
        vehiclenumTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        notifythroughmailBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        trpaLbl.setBackground(new java.awt.Color(204, 204, 255));
        trpaLbl.setFont(new java.awt.Font("Telugu MN", 3, 36)); // NOI18N
        trpaLbl.setForeground(new java.awt.Color(0, 102, 102));
        trpaLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transport.png"))); // NOI18N
        trpaLbl.setText("TRANSPORT REQUEST PROCESS AREA");

        etdLbl.setFont(new java.awt.Font("Telugu MN", 2, 14)); // NOI18N
        etdLbl.setText("Expected Time Of Delivery :");

        timeCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1:00", "2:00", "3:00", "4:00", "5:00", "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00" }));
        timeCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeCmbBoxActionPerformed(evt);
            }
        });

        timezoneCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        vehiclenumLbl.setFont(new java.awt.Font("Telugu MN", 2, 14)); // NOI18N
        vehiclenumLbl.setText("Vehicle Number:");

        vehiclenumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclenumTxtActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Telugu MN", 2, 14)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        notifythroughmailBtn.setFont(new java.awt.Font("Telugu MN", 2, 14)); // NOI18N
        notifythroughmailBtn.setText("Intimate Hospital through Mail");
        notifythroughmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifythroughmailBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vehiclenumLbl)
                                    .addComponent(etdLbl)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(517, 517, 517)
                                .addComponent(backBtn)))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notifythroughmailBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(timeCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(79, 79, 79)
                                    .addComponent(timezoneCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(vehiclenumTxt))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(trpaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(trpaLbl)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etdLbl)
                    .addComponent(timeCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timezoneCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiclenumLbl)
                    .addComponent(vehiclenumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(notifythroughmailBtn))
                .addContainerGap(506, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void timeCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeCmbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeCmbBoxActionPerformed
public void sendMailToCommunityMember(String to[], String subject, String message, String from, String password)
{
    String [] host = {"smtp@gmail.com"};
            Properties props = System.getProperties();
            props.put("mail.smtp.user", from);
            props.put("mail.smtp.port", 674);
            props.put("mail.smtp.host", host);
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.startttls.enable", "true");
JOptionPane.showMessageDialog(this, "New notification from Transport Department");
                    
                    
                  
            
}
    private void vehiclenumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclenumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehiclenumTxtActionPerformed

    private void notifythroughmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifythroughmailBtnActionPerformed
        request.setTime(timeCmbBox.getSelectedItem().toString() +" "+ timezoneCmbBox.getSelectedItem().toString()+" "+"VehicleNumber" +vehiclenumTxt.getText());
        String[] to = {"yashwanth.3b8@gmail.com"};
        sendMailToCommunityMember(to,
                "Alert from Transportation department",
                "The delivery details are for the equipment "+request.getEquipmentinfo()+" are" +request.getTime(),
                "doctortesting.test@gmail.com",
                "doctororganization");
        JOptionPane.showMessageDialog(null,"Email sent successfully");
        
    }//GEN-LAST:event_notifythroughmailBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TransportationWorkAreaJPanel twjp = (TransportationWorkAreaJPanel) component;
        twjp.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel etdLbl;
    private javax.swing.JButton notifythroughmailBtn;
    private javax.swing.JComboBox<String> timeCmbBox;
    private javax.swing.JComboBox<String> timezoneCmbBox;
    private javax.swing.JLabel trpaLbl;
    private javax.swing.JLabel vehiclenumLbl;
    private javax.swing.JTextField vehiclenumTxt;
    // End of variables declaration//GEN-END:variables
}
